openapi: 3.0.0
info:
  title: SPM API Document
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
# noauth
  /api/login:
    $ref: './paths/noauth/login.yaml'
  /api/signup:
    $ref: './paths/noauth/signup.yaml'
  /api/check/user:
    $ref: './paths/noauth/checkUser.yaml'
  /api/logout:
    $ref: './paths/noauth/logout.yaml'
# user
  /api/user/info:
    $ref: './paths/user/getUserInfo.yaml'
  /api/user/edit:
    $ref: './paths/user/editUserInfo.yaml'
  /api/user/edit/pwd:
    $ref: './paths/user/editUserPwd.yaml'
  /api/user/edit/img:
    $ref: './paths/user/editUserImg.yaml'
  /api/user/img:
    $ref: './paths/user/getUserImg.yaml'
# item
  /api/item/list:
    $ref: './paths/item/getItemList.yaml'
  /api/item/user-list:
    $ref: './paths/item/getItemListByUser.yaml'
  /api/item/upload:
    $ref: './paths/item/uploadItem.yaml'
# board
  /api/board/list:
    $ref: './paths/board/getBoardList.yaml'
  /api/board/upload:
    $ref: './paths/board/uploadBoard.yaml'


